
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      # Mount source code for hot-modification
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      # Prevent overwriting node_modules
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps Vite hot-reloading in some OS
    env_file:
      - .env
    networks:
      - streamvault-network

  backend:
    depends_on:
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      # Mount source code for hot-modification
      - ./backend/src:/app/src
      # Prevent overwriting node_modules
      - /app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    networks:
      - streamvault-network


  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - streamvault-network

networks:
  streamvault-network:
    driver: bridge
