[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; frame-src 'self' https://vidsrc.to https://*.vidsrc.to https://vidfast.pro https://*.vidfast.pro https://vidsrc.icu https://*.vidsrc.icu https://vidlink.pro https://*.vidlink.pro https://vidsrc.cc https://*.vidsrc.cc https://player.videasy.net https://*.videasy.net https://vidsrc.net https://*.vidsrc.net https://v2.vidsrc.me https://vercel.live https://*.vercel.live; script-src 'self' 'unsafe-inline' https://vercel.live https://*.vercel.live; connect-src 'self' https://api.themoviedb.org https://image.tmdb.org https://*.googleusercontent.com https://*.supabase.co https://*.auth0.com https://streamvault-backend-bq9p.onrender.com https://vercel.live https://*.vercel.live wss://*.supabase.co; img-src 'self' data: https://image.tmdb.org https://*.googleusercontent.com blob:; media-src 'self' blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; worker-src 'self' blob:; object-src 'none';"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "unsafe-none"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "accelerometer=*, autoplay=*, clipboard-write=*, encrypted-media=*, gyroscope=*, picture-in-picture=*, fullscreen=*"

[build]
  command = "npm run build"
  publish = "dist"


