-- Enable the pgvector extension for AI similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Table to store the 64-dimensional movie embeddings generated by the Two-Tower ItemTower
CREATE TABLE IF NOT EXISTS public."movie_embeddings" (
  "tmdbId" INTEGER PRIMARY KEY,
  "embedding" vector(64) NOT NULL,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Index for blazing fast Approximate Nearest Neighbor (ANN) search using Inner Product (ip)
-- Since Two-Tower uses dot product, vector_ip_ops is mathematically correct here.
CREATE INDEX IF NOT EXISTS "movie_embeddings_embedding_idx"
ON public."movie_embeddings"
USING hnsw ("embedding" vector_ip_ops);

-- Enable RLS
ALTER TABLE public."movie_embeddings" ENABLE ROW LEVEL SECURITY;

-- Expose read access to authenticated users / service role
CREATE POLICY "Enable read access for all" ON public."movie_embeddings"
    AS PERMISSIVE FOR SELECT
    USING (true);

-- Only service role can upload embeddings
CREATE POLICY "Enable insert/update access for service role only" ON public."movie_embeddings"
    AS PERMISSIVE FOR ALL
    TO service_role
    USING (true);

-- RPC function to find the top K nearest movies to a given user embedding
-- (This computes the dot product <user_vector, movie_vector> in real time and sorts by it)
CREATE OR REPLACE FUNCTION match_movies_from_user_embedding(
  query_embedding vector(64),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  "tmdbId" integer,
  "similarity" float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    me."tmdbId",
    -- Negative inner product operator <#> gives -1 * dot product
    -- Multiply by -1 again to get the actual positive dot product score
    (me.embedding <#> query_embedding) * -1 AS similarity
  FROM public."movie_embeddings" me
  -- Order by highest dot product first
  ORDER BY me.embedding <#> query_embedding ASC
  LIMIT match_count;
END;
$$;
